"""doc name are not unique

Revision ID: 54ae363789a1
Revises: 51215ee91d24
Create Date: 2025-05-20 13:32:49.547891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ae363789a1'
down_revision = '51215ee91d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('document_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_unique_constraint('document_name_key', ['name'])

    # ### end Alembic commands ###
