"""Add image_path to Document

Revision ID: 97ab43794f68
Revises: 67dad9078bf9
Create Date: 2025-05-20 09:19:00.151738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97ab43794f68'
down_revision = '67dad9078bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
        batch_op.drop_index('idx_report_data_jsonpath', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index('idx_report_data_jsonpath', ['data'], unique=False, postgresql_using='gin')
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
