"""Add text_content to report

Revision ID: 9cebb9712df3
Revises: 72b3b082acb4
Create Date: 2025-05-12 00:18:15.512357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cebb9712df3'
down_revision = '72b3b082acb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
        batch_op.drop_index('idx_report_data_trgm', postgresql_using='gin')
        batch_op.drop_index('idx_report_text_content_trgm', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index('idx_report_text_content_trgm', ['text_content'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_report_data_trgm', [sa.literal_column('(data::text)')], unique=False, postgresql_using='gin')
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))

    # ### end Alembic commands ###
