"""Alter text_content to citext2

Revision ID: b3b7b8bb534a
Revises: e0ec36101175
Create Date: 2025-05-12 00:30:23.398974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3b7b8bb534a'
down_revision = 'e0ec36101175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=postgresql.CITEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.Text(),
               type_=postgresql.CITEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
