"""doc name are not unique1

Revision ID: ced6d0c6c83e
Revises: 54ae363789a1
Create Date: 2025-05-20 13:47:14.876645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced6d0c6c83e'
down_revision = '54ae363789a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_owner_name', ['owner_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('uq_owner_name', type_='unique')

    # ### end Alembic commands ###
