"""Alter text_content to citext

Revision ID: e0ec36101175
Revises: 9cebb9712df3
Create Date: 2025-05-12 00:27:46.023357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0ec36101175'
down_revision = '9cebb9712df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=postgresql.CITEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('text_content',
               existing_type=sa.Text(),
               type_=postgresql.CITEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
